### ISSUE TITLE
No notes found

### ISSUE THREAD

**Issue by duqcyxwd** [ajgon/alfred2-quiver-search#1]
I have set up the library directory but when I do qs, there is no result fetched. Is the quivor's API changed?

**Comment by ajgon** [comment]
Hmm... no idea.

Can you please go to your "Alfred Settings => Workflows" pane, select "Quiver Search" and enable debugging? Then try your query again, and paste the output?

**Comment by jolantis** [comment]
I get the following debug error with Alfred:

```
Starting debug for 'Quiver Search'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: -e:11: invalid multibyte char (US-ASCII)
-e:11: invalid multibyte char (US-ASCII)
```

I'm using Quiver version 3.0.1 (71), for what it's worth.

Thanks for your help and nice Quiver workflow!

**Comment by duqcyxwd** [comment]
I get the different log.  The Alfred version is 2.8.2 and the Quiver version is 3.0.

```
[INFO: alfred.workflow.trigger.action] Processing output 'alfred.workflow.output.script' with arg '(
    "/Users/userabc/Dropbox/iMan/Quiver.qvlibrary"
)'
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Query too short</title><subtitle>The query needs to be at least 3 characters long</subtitle></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Query too short</title><subtitle>The query needs to be at least 3 characters long</subtitle></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>No notes found</title></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>No notes found</title></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>No notes found</title></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>No notes found</title></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>No notes found</title></item></items>
```

**Comment by lohiaguitar91** [comment]
I'm having the same issue as duqcyxwd

```
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>No notes found</title></item></items>
```

**Comment by t-jindai** [comment]
@ajgon I sent PR about this issue :+1: 

https://github.com/ajgon/alfred2-quiver-search/pull/2

**Comment by duqcyxwd** [comment]
@kashiro Thanks for your PR. This help some but It doesn't fix all. I query `spk`, it find something but when I press enter, nothing happen. The searching is wired too. It fetched spk but not spark. Spark is the keyword that in my document. 

I got this error:

```
Starting debug for 'Quiver Search'

[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Query too short</title><subtitle>The query needs to be at least 3 characters long</subtitle></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>No notes found</title></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Query too short</title><subtitle>The query needs to be at least 3 characters long</subtitle></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Query too short</title><subtitle>The query needs to be at least 3 characters long</subtitle></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Query too short</title><subtitle>The query needs to be at least 3 characters long</subtitle></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Query too short</title><subtitle>The query needs to be at least 3 characters long</subtitle></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item uid="11361D38-4315-4983-A486-5915FE417EFA" arg="quiver:///notes/11361D38-4315-4983-A486-5915FE417EFA"><title>local Spark config</title><subtitle>Work</subtitle><icon type="fileicon"></icon></item></items>
[INFO: alfred.workflow.input.scriptfilter] Processing output 'alfred.workflow.output.script' with arg 'quiver:///notes/11361D38-4315-4983-A486-5915FE417EFA'
```

**Comment by duqcyxwd** [comment]
There is another error I got. I am not sure related to this bug or not. When I type some random thing, It could be end up with 

![image](https://cloud.githubusercontent.com/assets/2519905/12656462/5245af7e-c5f6-11e5-88a6-8b54c2063eb8.png)

And here is the error message:

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `encode': "\xC2" on US-ASCII (Encoding::InvalidByteSequenceError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
    from -e:40:in `block in <main>'
    from -e:35:in `map'
    from -e:35:in `<main>'
```

**Comment by ajgon** [comment]
Hey guys,

Sorry for late reply, I'm going to investigate it right now. One question tough - are you typing any non-standard ASCII characters (diacritics, emoji etc.) ?

**Comment by ajgon** [comment]
@kashiro Thank you very much, I have no idea how it slipped through... :flushed: 

@duqcyxwd , @lohiaguitar91 This should solve the missing library problem.

**Comment by duqcyxwd** [comment]
@ajgon Thanks for your work and taking time look at this. 

I am sorry. I still get the same errors as before. For your question: I am not tying any non-standard ASCII characters, just regular characters.

There are two problems
- searching appearing a error "InvalidByteSequenceError" when typing regular characters.
- When a note found, "enter" doesn't bring the note out in Quiver.

**Comment by t-jindai** [comment]
@duqcyxwd 

the first problem was fixed [this commit](https://github.com/ajgon/alfred2-quiver-search/commit/0a5d5aa3d18a3eb18ed4be624b4c2851d8aaa59f) maybe. please try it.

---

Second problem is not problem. you can open quiver note using this `alfread workflow plugin` from quiver 3.0.1. (now 3.0.0)
According to [this ticket](https://github.com/HappenApps/Quiver/issues/361) that version will be release soon. Please wait :)

**Comment by duqcyxwd** [comment]
@kashiro Thanks for look at this. The bug is still there but with low frequency than before. It happens like kind of random. If some combination lead to the error, it keep happen.

**Comment by ylian** [comment]
Quiver 3.0.1 is released.
